### ISSUE TITLE
Implements UDF that returns the UAST from a file

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#193]
UDF that internally uses bblfsh. It should be like:

- `uast(content:BLOB, [lang:TEXT],[xpath:TEXT]) BLOB`

Also we will need another UDF to query again an uast

- `uast_xpath(uast:BLOB,xpath:TEXT) BLOB`

**Comment by erizocosmico** [comment]
Why does the `uast` function have the `xpath` arg?

**Comment by ajnavarro** [comment]
apply directly a xpath string to the tree result

**Comment by erizocosmico** [comment]
Ah, ok, so is a shortcut for `uast_xpath(uast(blob), xpath)` :+1:

**Comment by erizocosmico** [comment]
Also, a problem with `uast_xpath`: it returns a `[]*uast.Node`. We don't have arrays, so we can't really represent the multiple nodes returned. We _could_ use tuples (once they're merged), but that's kind of weird.

**Comment by ajnavarro** [comment]
we should check on bblfsh if they support right now send a request including the xpath string. If it's the case, we cannot do just a shortcut.

**Comment by erizocosmico** [comment]
Parse requests don't include the xpath right now, so the function would just be a shortcut if we want to implement it like that right now.

But yeah, maybe we should block this until we have arrays.

**Comment by erizocosmico** [comment]
Depends on https://github.com/src-d/go-mysql-server/issues/134

**Comment by erizocosmico** [comment]
@smola they don't have the same arguments.
In Engine is: `extract_uasts(path, blob[, lang])` and here is `uast(blob[, lang, xpath])`
