### ISSUE TITLE
Release: add Docker image

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase#203]
To simplify a new user's experience, it would be useful to have a Docker image with gitbase pushed somewhere, as one of the release artefacts of the project.

**Comment by ajnavarro** [comment]
The gitquery binary is in the releases. You can get the latest one here: https://github.com/src-d/gitquery/releases/tag/v0.10.0

**Comment by bzz** [comment]
So cool! Thank you for prompt fix, @erizocosmico ! 

I guess it will be on https://hub.docker.com/u/srcd/gitbase on the next release?
