### ISSUE TITLE
Benchmark gitbase

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#207]
We need a reproducible way to run a set of queries on a specific subset of repositories, to be able to compare gitbase versions (performance, CPU, memory and so on).

The set of queries is not complete but here is a draft: https://gist.github.com/smola/7013c2ce00788a36d9b57c66521a340d

For the data, we can start using a 10% of the PGA for testing. This 10% should contain always the same siva files.

**Comment by erizocosmico** [comment]
Currently blocked by #225

**Comment by erizocosmico** [comment]
Not blocked anymore. #225 addressed in #228
