### ISSUE TITLE
Squashed Join: Object not found error

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#213]
`Object not found error` happens sometimes using the squash joins rule. It appears to be because references can point to any object type, not only commits. Check if we are ignoring `object not found` error when a reference is pointing to a not-a-commit object.

**Comment by erizocosmico** [comment]
I think there's already a check in all ref iterators about this:

```
if ref.Type() != plumbing.HashReference {
	continue
}
```

**Comment by ajnavarro** [comment]
But that is not the problem, the problem is references pointing to blobs, or tags, per example. In borges if the reference is pointing to a tag (annotated tag), we try to resolve it. If the final object is not a Commit, that reference is discarded.
