### ISSUE TITLE
Add logs

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#217]
Add logs to gitbase, to be able to see what is happening on execution, and improve error reporting.

**Comment by erizocosmico** [comment]
What kind of logs do we want? Per row iteration? Interaction between iterators? For reporting errors (though I believe they are already reported via go-mysql-server)?

I could find a couple places where logging stuff makes sense but other than that it would mostly be like tracing again if we start putting logs like "starting foo", "finished foo"

**Comment by smola** [comment]
@erizocosmico What I miss is logging whatever "error" or fishy stuff that is done while reading a repo and swallowing silently. For example, if you ignore a reference because it points to a blob, it would be nice to get it logged.
