### ISSUE TITLE
refs table produces error if a repository has a HEAD pointing to non-existing reference

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#225]
`SELECT * FROM refs;` fails `(1105, 'unknown error: reference not found')` if a repository has a HEAD pointing to a non-existing reference.

This can happen, at least, in two situations:

* You have an empty repository (`git init --bare empty_repository.git`). `HEAD` will contain `ref: refs/heads/master` but `refs/heads/master` does not exist yet.
* siva files generated from borges also contain such `HEAD`.

Note that this was the error being masked by https://github.com/src-d/gitbase/issues/215

**Comment by erizocosmico** [comment]
We manually ask for head, but do not contemplate that may be missing right now. Should be an easy fix, though. Nice catch!

**Comment by erizocosmico** [comment]
Required by #207, as most of the queries will fail because of this
