### ISSUE TITLE
Enable nested folder support for git repositories

### ISSUE THREAD

**Issue by mcuadros** [src-d/gitbase#233]
Will be nice to support git repositories in nested folders, and not only in one level.
Maybe this helps: https://godoc.org/gopkg.in/src-d/go-git.v4#PlainOpenOptions

**Comment by erizocosmico** [comment]
This should be easy traversing the directories and looking for a `.git`, but how would we do this if there's a mix of bare and regular git repositories?

Even with that `PlainOpenOptions`, in the directory passed there could be more than one repository. How does it behave in that case?

**Comment by mcuadros** [comment]
Maybe its better provide a glob expression, instead of just go recursively to all the directories.
