### ISSUE TITLE
Build does not produce binaries

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase#255]
A week ago, very same instructions worked and I was able to build our awesome gitbase project, but now It seems that current `make packages` does not produce a valid binary on non-linux OSes any more.

### Steps to reproduce

[Following the CI](https://github.com/src-d/gitbase/blob/master/.travis.yml#L30):

```
export GOPATH="/tmp/gitbase-gopath"
mkdir -p $GOPATH
go get github.com/src-d/gitbase/cmd/gitbase
cd $GOPATH/src/github.com/src-d/gitbase

cd ./vendor/gopkg.in/bblfsh/client-go.v2
make dependencies
cd -
make dependencies
make packages
```

### Expected
a runnable binary at `./build/gitbase_darwin_amd64/gitbase`

### Actual
```
Makefile:17: warning: overriding commands for target `dependencies'
/private/tmp/gitbase-gopath/src/github.com/src-d/gitbase/.ci/Makefile.main:99: warning: ignoring old commands for target `dependencies'
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
/bin/bash: line 0: cd: /tmp/gitbase-gopath/src/github.com/src-d/gitbase/cmd/gitbase: No such file or directory
```

and then build output for Darwin arch is no executable, 
```sh
$./build/gitbase_darwin_amd64/gitbase
zsh: permission denied: ./build/gitbase_darwin_amd64/gitbase

$file ./build/gitbase_darwin_amd64/gitbase
./build/gitbase_darwin_amd64/gitbase: current ar archive
```

Please feel free to point to a better gitbase build instructions, in case I have missed something.

**Comment by smola** [comment]
I guess since `libuast` dependency was introduced, we cannot cross-compile for osx that easily, we probably need to add an actual build `osx` on Travis to produce it now.

**Comment by bzz** [comment]
I see.. Then, what would be an advised way of building on non-linux OSes for now?

**Comment by smola** [comment]
@bzz Sorry, I misunderstood. I thought you were talking about cross-compiling osx binaries from Linux. Build instructions should work in OSX AFAIK, so it is a bug if they do not.

**Comment by ajnavarro** [comment]
I think the problem should be fixed here: https://github.com/src-d/gitbase/pull/257

**Comment by bzz** [comment]
@smola at the end, it was not arch specific at all.

@ajnavarro tested locally and #257 resolves the issue, thank you!
