### ISSUE TITLE
Delete relation UDFs and modify squash rule to work with relation tables

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#274]
commit_has_tree()
commit_has_blob()
history_idx()

This should be done after all the changes on the existing tables, and the implementation of the new ones.

**Comment by erizocosmico** [comment]
Requires #280, #273 and #272

**Comment by erizocosmico** [comment]
- [ ] history_idx (feature on #280)
- [ ] commit_has_tree (feature on #281)
- [ ] commit_has_blob (feature pending)
