### ISSUE TITLE
macOS binary of releae 0.11.0 is only 130 bytes

### ISSUE THREAD

**Issue by catull** [src-d/gitbase#278]
The binary is only holding the top level directory without any files in it.

Please upload a full release, thank you.

**Comment by ajnavarro** [comment]
Thanks for the heads up!.

On this release, we added the integration with [bblfsh](https://github.com/bblfsh) to generate ASTs from source code, and it contains some cgo bindings. We are working to cross-compile that automatically from the CI.

Meanwhile, you can obtain the binaries from source: https://github.com/src-d/gitbase#installing-from-source

**Comment by catull** [comment]
I kind of depend on binaries ....

**Comment by erizocosmico** [comment]
I just uploaded a 0.11 binary release for macOS. Let me know if you have any other issues with it.
