### ISSUE TITLE
LANGUAGE and UAST functions should return NULL when they are not able to process a blob

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#300]
Right now they throw errors like: `unknown error: unable to parse the given blob using bblfsh: could not autodetect language`. We must log the error, but return NULL as a result.

Connections problems with bblfsh must throw an error.

**Comment by erizocosmico** [comment]
Done by #301

**Comment by kuba--** [comment]
Done by PR: https://github.com/src-d/gitbase/pull/301
