### ISSUE TITLE
Document which parts of SQL are supported

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#306]
During my friction log at #303 I could not find the documentation for what features of SQL are supported.

This issue is to track the creation of either a static documentation page, or a subcommand in `gitbase` that will show the verbs that are (not) supported.

**Comment by mcarmonaa** [comment]
@ajnavarro this information can be found in src-d/go-mysql-server's [README](https://github.com/src-d/go-mysql-server/blob/master/README.md).

Do you think mentioning and adding a link to it in the README is enough? or should I create a subcommand to show it?

**Comment by campoy** [comment]
I don't think the subcommand is needed, tbh.
Please add a link to the README, though.
