### ISSUE TITLE
Restrict CREATE INDEX queries

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase#326]
Now that we have `CREATE INDEX` it might be a good idea having a way to restrict who is allowed to perform it. For example, if we offered a gitbase-playground service open to the public.

Full user permission management might be overkill, but maybe we could have 2 default users for full-access and read-only access; `root` and `user`.

**Comment by ajnavarro** [comment]
Two options:

- Add a `--read-only` flag on gitbase startup to doesn't allow a set of queries using a rule.
- Have two hardcoded users: `gitbase` with read-only access, and root with all access.
