### ISSUE TITLE
Make Darwin compilation works

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#328]
Due to some cgo dependencies, we cannot cross-compile Darwin binaries. Compile them using a Darwin Travis node. Bblfsh cannot run on Darwin, so we will need to skip integration tests doing like here: https://github.com/bblfsh/client-go/blob/64416eecb5321d57179f787750f191fb6da045ce/client_test.go#L25

**Comment by kuba--** [comment]
what if we run `bblfsh` in docker

**Comment by kuba--** [comment]
>  Bblfsh cannot run on Darwin 
What does it mean? We cannot compile it on OSX?

**Comment by erizocosmico** [comment]
Bblfsh is run on docker right now, isn't it? It should not be a problem. I run it on docker on darwin and I have no problem with it.

Also, we might want to revisit the idea of compiling this on a darwin travis node. The build queue for OSX machines in travis is huge and the waiting time for them is _a lot_. It was so much that for enry we went with cross-compile from linux. An example of how to do that is on the enry makefile.

**Comment by erizocosmico** [comment]
I've been trying to cross-compile this from linux but it's been basically hell. xgo didn't do it either. So I'm gonna give up and just use a travis macOS instance to upload the binary.
