### ISSUE TITLE
GitBook Documentation

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#332]
Improve documentation creating it in Gitbook format

- [x] Create `docs` folder on the repository. All the Markdown files will be there.
- Main page
  - [x] Introduction 
  - [x] Motivation and scope
  - [x] Further reading
- Getting started
  - [ ] Using gitbase playground (add this when gitbase playground is deployed)
  - [x] Download and use the binary
  - [x] Running with docker
- Configuration
  - [x] Environment variables
  - [x] Executable params
- Supported syntax
  - [x] (link to go-mysql-server documentation)(#)
- Schema
  - [x] Main tables
  - [x] Relation tables
  - [x] Database diagram (https://www.quickdatabasediagrams.com/)
- Functions
  - [x] gitbase functions
  - [x] Standard functions (link to go-mysql-server documentation)(#)
- [x] Examples
  - [x] `SELECT refs.repository_id FROM refs NATURAL JOIN commits WHERE commits.commit_author_name = 'Javi Fontan' AND refs.ref_name='HEAD';`

- Join the community
  - [x] Chat
  - [x] Contributing
  - [x] Reporting bugs

## README changes

- Remove from README and point to documentation
  - [ ] Config
  - [ ] Tables
  - [ ] Functions
  - [ ] Examples

**Comment by eiso** [comment]
Really happy to see the work being done here!
