### ISSUE TITLE
Proposal: Make squash join rule active by default

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#340]
We are having a lot of performance reports due to the speed of some joins when that rule is not active, making the query 10x slower.

To avoid that, we can activate the squash join rule by default, and add an environment variable to deactivate it if the user needs it.

Also, having the explain statement, and improving gitbase documentation with the columns of the different tables used to make the squash, people can figure out why a query is slower than other.

WDYT: @mcuadros @smola @src-d/data-retrieval ?

**Comment by erizocosmico** [comment]
I think we should wait until #338 is merged before doing this, since it's a bug affecting squashing.

**Comment by erizocosmico** [comment]
Closed by #345
