### ISSUE TITLE
Make script to automate upgrading go-mysql-server version

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase#348]
We could have a simple script that:

- reads the current version of go-mysql-server
- receives the new version as parameter
- replaces all instances of the previous version with the new one across the project
- runs `dep ensure -v`

This would assure nobody forgot to update the docs.

Or, we could have a CI check that ensures both versions are the same.

**Comment by kuba--** [comment]
Can be related to https://github.com/src-d/gitbase/pull/362

**Comment by kuba--** [comment]
pr:https://github.com/src-d/gitbase/pull/362

**Comment by kuba--** [comment]
Run script as follows:
```
./rev-upgrade.sh "gopkg.in/src-d/go-mysql-server.v0" "dcc1c537eb7e2bc20ce69d03732e8aa8feaa8612"
```

**Comment by kuba--** [comment]
usage:
```
./rev-upgrade.sh <project's name from Gopkg.lock> <project's new revision>
```

**Comment by ajnavarro** [comment]
Closed by: https://github.com/src-d/gitbase/pull/362
