### ISSUE TITLE
Do not fail a query for bblfsh error in one row

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase#369]
Right now if I run a query asking for a `UAST()` column, the whole query returns an error if bblfsh fails to parse any of the rows.

This is inconvenient because a file with a syntax error can prevent any query from working for all the other files.

```
MySQL [(none)]> select UAST(blob_content, LANGUAGE(file_path, blob_content)) from files where repository_id="demo";
ERROR 1105 (HY000): unknown error: unable to parse the given blob using bblfsh: Syntax error on token "publi", public expected
```

I think there should be a way to get all the rows, with an empty UAST value where bblfsh failed.

What would be awesome is to have these bblfsh errors for each failed UAST request. Maybe there is a way to make `UAST()` return either UAST, or error messages?

**Comment by ajnavarro** [comment]
Thanks for the heads up!

The UAST function shouldn't fail, that's a bug, but:

- A UDF cannot return a different kind of types randomly, only one or nil.
- The errors messages will be logged on gitbase server.
