### ISSUE TITLE
Upgrade bblfsh to sdk v2

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase#393]
It would be great to soon be able to use the new semantic concepts/UAST structure from gitbase.

cc @dennwc @ajnavarro @smola

**Comment by erizocosmico** [comment]
I can't see any v2 in the sdk releases. Is that something not yet released?

**Comment by smola** [comment]
@erizocosmico Not released yet.

**Comment by erizocosmico** [comment]
AFAIK it was already released, right?

**Comment by smola** [comment]
@erizocosmico Yes, sdk v2 was released, but not all drivers are updated yet. So it should be possible to start the migration now, but not ready for merging.

cc @juanjux @dennwc to provide further insights on when gitbase should upgrade.

**Comment by dennwc** [comment]
Please wait for libuast and client-go to be ready. Will track the progress in https://github.com/bblfsh/sdk/issues/293.

**Comment by jfontan** [comment]
Done in #439
