### ISSUE TITLE
MySQL authentication error

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase#394]
I am running gitbase based on the latest binary (0.14).

```
$ gitbase server -v -g ~/projects/enginerepos-srcd/ --host 127.0.0.1 -p 3306
```

I am using the mysql-clients package (https://aur.archlinux.org/packages/mysql-clients/) on Arch Linux distro.

```
$ mysql --version
mysql  Ver 8.0.11 for Linux on x86_64 (MySQL Community Server (GPL))
```

The behaviour I am getting is:

```
$ mysql -q -u root -h 127.0.0.1 
ERROR 2012 (HY000): Client asked for auth caching_sha2_password, but server wants auth mysql_native_password
```

**Comment by smola** [comment]
@eiso I think you might be able to workaround this by adding `--default-auth=mysql_native_password` flag. See [relevant docs](https://dev.mysql.com/doc/refman/8.0/en/native-pluggable-authentication.html).

**Comment by erizocosmico** [comment]
Turns out the default authentication method now is `caching_sha2_password` as of 8.0. The solution would be to use what was pointed out by @smola, but maybe we can add support for `caching_sha2_password` in go-mysql-server so the login is seamless.

**Comment by smola** [comment]
It might also be possible to fix auth method negotiation to keep maximum interoperability across versions: https://dev.mysql.com/doc/internals/en/determining-authentication-method.html

**Comment by erizocosmico** [comment]
I've been checking in go-vitess if there's a way to restrict which capabilities are sent from the server in the connection, [but they're hardcoded](https://github.com/src-d/go-vitess/blob/master/mysql/server.go#L415-L426), so I don't think we're gonna be able to solve it this way unless we do the change directly inside go-vitess, which I'm not sure is something we want to do.
