### ISSUE TITLE
Missing contributing guidelines document

### ISSUE THREAD

**Issue by marnovo** [src-d/gitbase#399]
Missing the [CONTRIBUTING.md](https://github.com/src-d/guide/blob/master/engineering/documentation.md#contributingmd) (also let's remember to refer to it in the README.md).

**Comment by ajnavarro** [comment]
Related: https://github.com/src-d/gitbase/pull/293

What should we do @smola ?

**Comment by smola** [comment]
@ajnavarro IMHO just merge the CONTRIBUTING.md you prepared. Any further amendments about development environment can be made later.

**Comment by erizocosmico** [comment]
I guess we can just close this now, right?
