### ISSUE TITLE
Syntax error using `index` column unqualified

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase#408]
This fails:

```sql
SELECT * FROM ref_commits WHERE index = 0;
```

With:

```
ERROR 1105 (HY000): unknown error: syntax error at position 38 near 'index'
```

This does not fail:

```sql
SELECT * FROM ref_commits r WHERE r.index = 0;
```

Note that this is an error in MySQL too, because INDEX is a reserved keyword. We should rename `index` to something else, like `commit_index` or something like that. WDYT? @ajnavarro @src-d/data-retrieval

**Comment by ajnavarro** [comment]
I would say to do not call it `commit_index` because is something that is not coming from a commit itself. We can call it just `idx`.

**Comment by erizocosmico** [comment]
What do you think about `history_index`? I feel like `idx` might be too arcane for many users (even if for some it's pretty obvious).

**Comment by ajnavarro** [comment]
LGTM
