### ISSUE TITLE
siva exception for HEAD reference

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase#423]
When using `siva` files you see a **LOT** of debug messages for trying to get HEAD:

```
DEBU[4562] unable to get HEAD of repository              repo=6db1a31e58ee15c448448139e7d3a9e72b14268f.siva
DEBU[4562] ignoring reference, it's not a hash reference  ref=HEAD type=symbolic-reference
```

I suggest disabling this check/logging for siva files, it makes the logging very verbose and hard to use as a user.

**Comment by ajnavarro** [comment]
Maybe we can just remove that debug log, is not giving needed info to users. WDYT @src-d/data-retrieval ?

**Comment by erizocosmico** [comment]
I think it's ok to just remove it

**Comment by ajnavarro** [comment]
It still appears.
