### ISSUE TITLE
Documentation - Link to introduction page missing

### ISSUE THREAD

**Issue by tsolakoua** [src-d/gitbase#432]
Related to: https://github.com/src-d/devrel/issues/81

**Comment by erizocosmico** [comment]
I can't see that link you mention:

**Comment by tsolakoua** [comment]
- There is no [introduction](https://docs.sourced.tech/gitbase/) link that can be reached from the other pages (apart from the connection ```Previous - Introduction``` in the [join the community](https://docs.sourced.tech/gitbase/join-the-community). It would be nice to have a link pointing to intro from any other page of the documentation. For example:

<img width="332" alt="screen shot 2018-08-17 at 12 48 32 pm" src="https://user-images.githubusercontent.com/15012967/44262617-fb602900-a21b-11e8-970b-b277c1489db5.png">

**Comment by erizocosmico** [comment]
Ah, ok, you mean there is no link to get to the intro from other pages. You just have to click on the gitbase title and it gets you to the main page.

**Comment by tsolakoua** [comment]
Ok, I hadn't noticed :) then we can leave it like that.

**Comment by tsolakoua** [comment]
@erizocosmico I think it can be closed, right?
