### ISSUE TITLE
Add a intermediate cache for language UDF

### ISSUE THREAD

**Issue by jfontan** [src-d/gitbase#442]
language UDF can be very slow when querying a lot of files. Sometimes this is executing language for the same file multiple times. For example, if we iterate the `files` table the same file is multiplied by the number of commits.

It could be good to add an intermediate cache so the results from previous run can be used instead of finding again the language. We can use an LRU using the file name and blob hashes. We may be able to use the hash of the first bytes of the blob that enry uses to speed up the process.

**Comment by ajnavarro** [comment]
related: https://github.com/src-d/enry/pull/156
