### ISSUE TITLE
surprising performance issue

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#443]
I just ran this query on top of github.com/golang/go:

```sql
  SELECT
  	LANGUAGE(t.tree_entry_name, b.blob_content) as lang,
	t.tree_entry_name as name,
       b.blob_content as code
  FROM refs r 
       JOIN commits c ON r.commit_hash = c.commit_hash
       JOIN commit_trees ct ON c.commit_hash = ct.commit_hash
       JOIN tree_entries t ON ct.tree_hash = t.tree_hash
       JOIN blobs b ON t.blob_hash = b.blob_hash
```

This finishes in 0.65s :tada:

Unfortunately this other request takes forever:

```sql
  SELECT
	t.tree_entry_name as name,
        b.blob_content as code
  FROM refs r 
       JOIN commits c ON r.commit_hash = c.commit_hash
       JOIN commit_trees ct ON c.commit_hash = ct.commit_hash
       JOIN tree_entries t ON ct.tree_hash = t.tree_hash
       JOIN blobs b ON t.blob_hash = b.blob_hash
   WHERE LANGUAGE(t.tree_entry_name, b.blob_content) = 'go'
```

Trying to see whether I could find a workaround I wrote this second query:

```sql
SELECT name, code
FROM 
(
  SELECT
	LANGUAGE(t.tree_entry_name, b.blob_content) = 'go' as lang,
	t.tree_entry_name as name,    
        b.blob_content as code
  FROM refs r 
       JOIN commits c ON r.commit_hash = c.commit_hash
       JOIN commit_trees ct ON c.commit_hash = ct.commit_hash
       JOIN tree_entries t ON ct.tree_hash = t.tree_hash
       JOIN blobs b ON t.blob_hash = b.blob_hash
) as blobs
WHERE lang = 'go'
```

Both of these requests take too long for me to wait.

**Comment by ajnavarro** [comment]
@campoy could you send the result of the queries but adding at the beginning `EXPLAIN FORMAT=tree` please? It will give us really valuable info about query performance.

**Comment by kuba--** [comment]
```

SELECT  	
	t.tree_entry_name AS NAME,
       b.blob_content AS CODE
  FROM refs r 
       JOIN commits c ON r.commit_hash = c.commit_hash
       JOIN commit_trees ct ON c.commit_hash = ct.commit_hash
       JOIN tree_entries t ON ct.tree_hash = t.tree_hash
       JOIN blobs b ON t.blob_hash = b.blob_hash
  WHERE LANGUAGE(t.tree_entry_name, b.blob_content) = 'Go';
```
<img width="293" alt="screen shot 2018-10-04 at 09 54 35" src="https://user-images.githubusercontent.com/4056521/46460204-8c369800-c7bb-11e8-8676-995b0866e894.png">

**Comment by kuba--** [comment]
There is no index involved, because so far we cannot create an index across multiple columns and `LANGUAGE(t.tree_entry_name, b.blob_content)` will require that.

**Comment by erizocosmico** [comment]
Can you try with this query? This would be the correct query for what you want based on the data you're selecting.

```sql
  SELECT
	t.tree_entry_name as name,
        b.blob_content as code
  FROM tree_entries t
  NATURAL JOIN blobs b
  WHERE LANGUAGE(t.tree_entry_name, b.blob_content) = 'go'
```

The one you provided is unnecessarily complicated. If you only want tree entries and blobs, there's no need to involve refs, commits and commit_trees. Those joins without any kind of filter generate a massive amount of data that you don't need (not to mention duplicates).

Nonetheless, I will investigate the performance difference between the first and the other two.

**Comment by erizocosmico** [comment]
I have executed all three queries and the results in terms of time are quite similar:

- First query: 1069809 rows in 1m34.779148952s
- Second query: 760122 rows in 1m26.175958486s
- Third query: 760122 rows in 1m36.166300878s

Most likely, what happened is that you saw no output because every single row was being filtered due to `LANGUAGE(..., ...) = 'go'`. It should be `Go` instead of `go`, which is the correct enry result.

I think for the sake of user friendlyness we should either output lowercased language names or specify in the documentation the correct names for all languages. WDYT @ajnavarro?

Correct second query:

```sql
  SELECT
	t.tree_entry_name as name,
        b.blob_content as code
  FROM refs r 
       JOIN commits c ON r.commit_hash = c.commit_hash
       JOIN commit_trees ct ON c.commit_hash = ct.commit_hash
       JOIN tree_entries t ON ct.tree_hash = t.tree_hash
       JOIN blobs b ON t.blob_hash = b.blob_hash
   WHERE LANGUAGE(t.tree_entry_name, b.blob_content) = 'go'
```

Correct third query: 

```sql
SELECT name, code
FROM 
(
  SELECT
	LANGUAGE(t.tree_entry_name, b.blob_content) as lang,
	t.tree_entry_name as name,    
        b.blob_content as code
  FROM refs r 
       JOIN commits c ON r.commit_hash = c.commit_hash
       JOIN commit_trees ct ON c.commit_hash = ct.commit_hash
       JOIN tree_entries t ON ct.tree_hash = t.tree_hash
       JOIN blobs b ON t.blob_hash = b.blob_hash
) as blobs
WHERE lang = 'Go'
```

That said, if what you were aiming for was getting all Go code from the repo, this is a more concise and less expensive query to to that:

```sql
SELECT tree_entry_name as name, blob_content as code
FROM tree_entries NATURAL JOIN blobs
WHERE LANGUAGE(tree_entry_name, blob_content) = 'Go'
```

**Comment by kuba--** [comment]
personally I think LANGUAGE should return all lowercases. There is no point why we need to capitalise lang's name.

**Comment by erizocosmico** [comment]
@kuba-- totally agree

**Comment by ajnavarro** [comment]
@erizocosmico @kuba-- I cannot think in any other downside than old queries that are using correct Enry strings will fail. Maybe is totally OK. WDYT @smola ?

**Comment by smola** [comment]
UAST might break if you change LANGUAGE to lowercase. You should check that. Other than that, it should be ok.

**Comment by smola** [comment]
Another option is adding support for `LOWER` and `UPPER`

**Comment by erizocosmico** [comment]
@smola UAST already lowercases everything, afaik. But lower and upper + adding to the docs the list of languages returned by enry sounds good too.

**Comment by smola** [comment]
:+1: to adding a list of languages by enry. bblfsh has the same issue. We could document that list in src-d/enry README.md and link it from both projects.
See https://github.com/bblfsh/documentation/issues/191

**Comment by ajnavarro** [comment]
Opening new issue to handle the real problem: #658
