### ISSUE TITLE
unexpected crash

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#444]
The following request is being ran on top of the Go repo.

```sql
SELECT f.repository_id, f.file_path,
       LANGUAGE(f.file_path, f.blob_content) AS lang, f.blob_content,
       UAST(f.blob_content, LANGUAGE(f.file_path, f.blob_content)) AS uast
FROM   files AS f
       JOIN commit_files cf ON
            f.repository_id=cf.repository_id AND
            f.file_path=cf.file_path AND
            f.blob_hash=cf.blob_hash AND
            f.tree_hash=cf.tree_hash
       JOIN refs ON
            cf.repository_id = 'go' AND
            refs.repository_id = 'go' AND
            cf.commit_hash = refs.commit_hash
WHERE  ref_name = 'HEAD'
       AND f.file_path REGEXP('.*\.go')
```

After a dozen of seconds I just see the error `unknown error: rpc error: code = Unavailable desc = transport is closing` both in `gitbase-web`, `engine`, and `mysql`.

The logs of the container do not indicate any issue.

<details><code><pre>
23:54 ~ ➜  docker logs srcd-cli-gitbase
time="2018-08-28T05:53:54Z" level=debug msg="git repositories directory added" dir=/opt/repos
time="2018-08-28T05:53:54Z" level=debug msg="repository added" path=/opt/repos/go
time="2018-08-28T05:53:54Z" level=debug msg="registered database to catalog" db=
time="2018-08-28T05:53:54Z" level=debug msg="registered all available functions in catalog"
time="2018-08-28T05:53:54Z" level=debug msg="created index storage"
time="2018-08-28T05:53:54Z" level=debug msg="established connection with pilosa"
time="2018-08-28T05:53:54Z" level=debug msg="registered pilosa index driver"
time="2018-08-28T05:53:54Z" level=info msg="squash tables rule is enabled"
time="2018-08-28T05:53:54Z" level=info msg="server started and listening on 0.0.0.0:3306"
time="2018-08-28T05:53:59Z" level=info msg="NewConnection: client 1"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="SHOW TABLES"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE remotes"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE tree_entries"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commit_blobs"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commit_trees"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE refs"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE files"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE ref_commits"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE repositories"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE blobs"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commit_files"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commits"
time="2018-08-28T05:54:04Z" level=debug msg="executing query" query="SELECT f.repository_id, f.file_path,\n       LANGUAGE(f.file_path, f.blob_content) AS lang, f.blob_content,\n       UAST(f.blob_content, LANGUAGE(f.file_path, f.blob_content)) AS uast\nFROM   files AS f\n       JOIN commit_files cf ON\n            f.repository_id=cf.repository_id AND\n            f.file_path=cf.file_path AND\n            f.blob_hash=cf.blob_hash AND\n            f.tree_hash=cf.tree_hash\n       JOIN refs ON\n            cf.repository_id = 'go' AND\n            refs.repository_id = 'go' AND\n            cf.commit_hash = refs.commit_hash\nWHERE  ref_name = 'HEAD'\n       AND f.file_path REGEXP('.*\\.go') LIMIT 100"
</pre></code></details>

**Comment by campoy** [comment]
I think the issue is related to a mistake on the `JOIN refs ON` statement, which includes `= go`.
I'm almost sure that's wrong.

In that case the error should be clear and fail on parsing the query, not after a while running.

**Comment by campoy** [comment]
Actually, even with the correct `JONS ref ON cf.repository_id = refs.repository_id` the request still crashes in the same way.

**Comment by ajnavarro** [comment]
I'm not able to reproduce the error, but appears to be related with bblfsh. Can you check bblfsh logs please?

**Comment by kuba--** [comment]
I don't know if it's related, but I started creating an index on `refs.ref_name` (it takes some time), but in the middle I run this query and mysql panic:
```
gitbase_1      | time="2018-08-31T12:36:27Z" level=error msg="mysql_server caught panic:\nruntime error: invalid memory address or nil pointer dereference\n/usr/local/go/src/runtime/panic.go:502 (0x42d978)\n/usr/local/go/src/runtime/panic.go:63 (0x42c9ed)\n/usr/local/go/src/runtime/signal_unix.go:388 (0x442939)\n/go/src/github.com/src-d/gitbase/vendor/github.com/pilosa/pilosa/field.go:175 (0xdc9d1f)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosalib/lookup.go:134 (0xdca0f1)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosalib/lookup.go:134 (0xdca0f1)\n/go/src/github.com/src-d/gitbase/squash_iterator.go:584 (0xba5602)\n/go/src/github.com/src-d/gitbase/squash_iterator.go:1670 (0xbac6fe)\n/go/src/github.com/src-d/gitbase/squash_iterator.go:3154 (0xbb544d)\n/go/src/github.com/src-d/gitbase/squash_iterator.go:3379 (0xbb700a)\n/go/src/github.com/src-d/gitbase/squash_iterator.go:3436 (0xbb778d)\n/go/src/github.com/src-d/gitbase/internal/rule/squashjoins.go:1045 (0xc7d8c0)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/project.go:64 (0x7f97f6)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/limit.go:35 (0x7f7c96)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/pushdown.go:244 (0xb52250)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/engine.go:66 (0xb7c154)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-mysql-server.v0/server/handler.go:89 (0xb7cfb0)\n/go/src/github.com/src-d/gitbase/vendor/gopkg.in/src-d/go-vitess.v0/mysql/server.go:338 (0xb3ac3f)\n/usr/local/go/src/runtime/asm_amd64.s:2361 (0x459da0)\n"
```

**Comment by jfontan** [comment]
I've managed to produce that error killing the bblfshd driver process. This can happen for example when it's consuming too much memory and generates a OOM error. In my case the driver was using almost 7Gb of ram when I've killed it.

I can only think on retrying bblfshd calls when this error happens. Ideas? @src-d/data-retrieval

**Comment by kuba--** [comment]
Circuit breaker.

**Comment by kuba--** [comment]
Again, I could not reproduce it. I tried to kill stop bblfsh or remove drivers in a meantime of running query. Got errors but no crash.
Regarding of retry logic - we already retry connect to Bblfsh 10 times (with total max 30) before we return an error.
So we can just improve the logic by introducing Circuit breaker: https://github.com/sony/gobreaker

WDYT - @src-d/data-retrieval ?

**Comment by jfontan** [comment]
gitbase does not crash, it stops the query with error. The panics from bblfsh should be captured with https://github.com/src-d/gitbase/commit/cc7165074c7015a404e4c6091dca9e6c18df9ed5

We may want to have some similar to `GITBASE_SKIP_GIT_ERRORS` for UAST or any other error.

**Comment by ajnavarro** [comment]
A function shouldn't fail. On UAST case, it should return a `null` result if it is not able to get the UAST.

**Comment by ajnavarro** [comment]
@kuba-- Open a separated issue if you don't mind and explain a bit on it the advantages of having a circuit breaker and the cons if any (I think it's not the solution for that bug, just an improvement).
