### ISSUE TITLE
use oniguruma with enry in language function

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#452]
Add the possibility to compile gitbase using oniguruma integration with enry, to speed up language function.

Getting the language from 1M files:
- using Go regular expressions: ~17 min
- using oniguruma: ~4 min

We need to think about how to release binaries in a proper way including this.

**Comment by erizocosmico** [comment]
We already use cgo for libuast and have a setup for releasing macOS binaries, so I think there will be no problem in using oniguruma with the current setup.
