### ISSUE TITLE
Copying Commands in documentation

### ISSUE THREAD

**Issue by tsolakoua** [src-d/gitbase#456]
When copying terminal commands, it gets copied also the symbol ```$```, so when someone pastes it in the terminal, has to go at the beginning of the line and remove it. Should be kept like that or remove the ```$```?

https://github.com/src-d/devrel/issues/81

**Comment by erizocosmico** [comment]
That's very common in technical documentation, the `$` at the beginning is just to tell the user the following is a terminal command.
For example, when you want to show command and output:

```
$ somecommand --withflags
result of that command
```

**Comment by tsolakoua** [comment]
Yes, that's right, but when you click on copying, it copies the command + the ```$``` and maybe it's a bit annoying to go at the beginning of your terminal to delete it. I don't know if it's possible while copying to not discard the symbol.

**Comment by erizocosmico** [comment]
Oh, I didn't know GitBook had a copy button. Then, if there is no output we should remove the $ to make it copiable. WDYT @ajnavarro?
