### ISSUE TITLE
Drop index hangs

### ISSUE THREAD

**Issue by kuba--** [src-d/gitbase#463]
I tested *gitbase* with _not_ the latest *mysql* (rev: "090a17d38c22a28eccf631f400c11704f65bb6ce").

I encountered weird behaviour. After I `SHOW INDEXES`, a `DROP` query hangs.
I can create and immediately drop index, I can create, use and drop, but after I run `show`, the drop operations hangs.

I tested against:
```sql
CREATE INDEX email_idx ON commits USING pilosalib (commit_author_email);

SHOW INDEXES FROM commits;

DROP INDEX email_idx ON commits;
```

Maybe after upgrading mysql the problem will be solved. So far it exists on master.

**Comment by erizocosmico** [comment]
Show indexes must be retaining indexes but not releasing them

**Comment by kuba--** [comment]
Maybe it's a problem with `pilosalib`  (I tested with `pilosalib`). 
In practice I tested manually against gitbase.

**Comment by erizocosmico** [comment]
works with pilosalib too

**Comment by kuba--** [comment]
Hmm, so have to debug deeper in my environment (gitbase master).

**Comment by erizocosmico** [comment]
Been trying a little more and still cannot reproduce it

**Comment by kuba--** [comment]
I tried reproduce it again (this time on master) and I cannot, so looks that it's fixed or maybe it was my client.
