### ISSUE TITLE
invalid type: [][]string

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/gitbase#495]
I run the following query:

```sql
SELECT files.repository_id, files.file_path,
    ARRAY_LENGTH(uast_extract(UAST(
        files.blob_content,
        LANGUAGE(files.file_path, files.blob_content),
        '//*[@roleFunction]'), "internal_type")
    ) as functions
FROM files
WHERE files.file_path = "common.go"
ORDER BY functions DESC
```

with the most recent gitbase docker image. It errors with:

```
unknown error: invalid type: [][]string
```

What's funny is if I change the xpath:

```sql
SELECT files.repository_id, files.file_path,
    ARRAY_LENGTH(uast_extract(UAST(
        files.blob_content,
        LANGUAGE(files.file_path, files.blob_content),
        '//*[@roleFunction and @roleDeclaration]'), "internal_type")
    ) as functions
FROM files
WHERE files.file_path = "common.go"
ORDER BY functions DESC
```

Then I don't get this error (but I get 0 functions in go-git/common.go instead of 1 which is still wrong).

**Comment by vmarkovtsev** [comment]
Another example:

```sql
SELECT files.repository_id, files.file_path,
      ARRAY_LENGTH(uast_extract(uast_xpath(UAST_mode("annotated", files.blob_content, "Go"), "//*[@roleFunction and @roleDeclaration]"), "token")) as functions
FROM files
WHERE files.file_path = "common.go"
```

**Comment by mcarmonaa** [comment]
About the error `unknown error: invalid type: [][]string` a fix is coming.

On the other hand, there is some issues with the queries:
```sql
SELECT files.repository_id, files.file_path,
    ARRAY_LENGTH(uast_extract(UAST(
        files.blob_content,
        LANGUAGE(files.file_path, files.blob_content),
        '//*[@roleFunction]'), "internal_type")
    ) as functions
FROM files
WHERE files.file_path = "common.go"
ORDER BY functions DESC
```
With this query you are using `uast` and by default it returns a `semantic` uast so I don't think that the xpath query `//*[@roleFunction]` works on it.

The `uast_extract` function have special selectors for common properties (`@token`, `@role`, `@type`, `@startpos`, `@endpos`) check [the examples](https://docs.sourced.tech/gitbase/using-gitbase/examples#extracting-information-from-uast-nodes).

We should clarify too that `uast_extract` will return an array for each one of the nodes given to the function even if that node doesn't have the requested property (in such case an empty array is returned).

So this query:
```
SELECT files.repository_id, files.file_path,
      ARRAY_LENGTH(uast_extract(uast_xpath(UAST_mode("annotated", files.blob_content, "Go"), "//*[@roleFunction and @roleDeclaration]"), "token")) as functions
FROM files
WHERE files.file_path = "common.go"
```

and this query
```
SELECT files.repository_id, files.file_path,
      ARRAY_LENGTH(uast_xpath(UAST_mode("annotated", files.blob_content, "Go"), "//*[@roleFunction and @roleDeclaration]"), "@token") as functions
FROM files
WHERE files.file_path = "common.go"
```

will return the same number, even if none of the nodes have a property `token` (the result would be an array of empty arrays)).

**Comment by ajnavarro** [comment]
@mcarmonaa I think we should need a new UDF, like `unnest` from postgres, WDYT?

**Comment by ajnavarro** [comment]
@mcarmonaa also we can have a look to something more mySQL specific: https://dev.mysql.com/doc/refman/8.0/en/json-function-reference.html

**Comment by mcarmonaa** [comment]
@ajnavarro we could return `extract_uast` as a JSON type and manage the result implementing some of those json functions from mysql.

What I can't see is the cases of usage. I don't know what is what we wanna get from the `uast_extract` results to decide which functions we should implement. The same with the unnest.

**Comment by ajnavarro** [comment]
per example, to be able to count functions, we can do something like:

```sql
[...]
ARRAY_LENGTH(
	JSON_EXTRACT(
		UAST_EXTRACT(
			UAST_XPATH(
				UAST_MODE(
					"annotated",
					files.blob_content,
					lang
				),
				'//*[@roleFunction and @roleDeclaration]'
			),
			"token"
		)
		"$[*]"
	)
)
```

**Comment by mcarmonaa** [comment]
Ok, so we can start changing the returned type of the `uast_extract` and implementing `json_extract` then. :+1:

**Comment by vmarkovtsev** [comment]
I do feel the glory of abstraction layers in `ARRAY_LENGTH(JSON_EXTRACT(UAST_EXTRACT(UAST_XPATH(UAST_MODE(` to count functions but maybe we can simplify a bit? E.g., we are using `UAST_EXTRACT` as a hack to get an array of the same length as the filtered nodes, so if `UAST_XPATH` returns a list of nodes we could `ARRAY_LENGTH` it directly...

Tagging @campoy for comments.

**Comment by vmarkovtsev** [comment]
According to the numerous examples of BigQuery usage over GitHub, counting stuff is close to #1 top frequent pattern.
