### ISSUE TITLE
RC releases are tagged as latest in docker hub.

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase#501]
Right now `latest` points to `v0.17.0-rc.3`, and it should probably be updated only when the final version is released.
https://hub.docker.com/r/srcd/gitbase/tags/

**Comment by smola** [comment]
This is something we might want to fix globally in src-d/ci.

**Comment by jfontan** [comment]
@smola I'm fixing this for gitbase but will open a PR for ci. A new variable called `IS_RELEASE` that is `true` when it matches a version regexp. Then we can do:

```
DOCKER_PUSH_LATEST=$${IS_RELEASE} make docker-push
```

**Comment by ajnavarro** [comment]
Temporal fix for gitbase on https://github.com/src-d/gitbase/pull/513

**Comment by jfontan** [comment]
CI support in https://github.com/src-d/ci/pull/87

**Comment by ajnavarro** [comment]
@erizocosmico we should undo the fix on gitbase and use the CI one.

**Comment by erizocosmico** [comment]
This is blocked until the PR is merged on src-d/ci

**Comment by ajnavarro** [comment]
Not blocked anymore. Merged on CI repo.
