### ISSUE TITLE
[request] Export uast_utils marshal/unmarshal functions

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase#506]
This is not a blocker, but it would be good to have at least [`unmarshalNodes`](https://github.com/src-d/gitbase/blob/master/internal/function/uast_utils.go#L173) exported so it can be used by gitbase-web.

**Comment by mcarmonaa** [comment]
@ajnavarro  should we close this then?

**Comment by ajnavarro** [comment]
We will add documentation explaining the output format of that Functions on documentation. Can you open an issue for this @mcarmonaa ? thanks.
