### ISSUE TITLE
Cannot create an index for blob's content

### ISSUE THREAD

**Issue by kuba--** [src-d/gitbase#521]
Following query:
```
CREATE INDEX blob_idx ON blobs USING pilosa (blob_content);
```
returns an error:
```
unknown error: expression "blobs.blob_content" with type {} cannot be indexed
```

**Comment by ajnavarro** [comment]
Is on purpose: https://github.com/src-d/go-mysql-server/blob/dedbd68bcc6d14308ca13cdf6394577e2dd42f60/sql/plan/create_index.go#L117

But we can improve the output error.

**Comment by ajnavarro** [comment]
@kuba-- shall we close this one?

**Comment by kuba--** [comment]
yes
