### ISSUE TITLE
Support LOWER and UPPER

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#562]
LOWER and UPPER are necessary for case insensitive processing.

For instance, sorting repositories by their id in alphabetical way is currently impossible.

```sql
SELECT *
FROM repositories
ORDER BY LOWER(repository_id)
```

Will not work, and without `LOWER` will print first upper then lower case.

**Comment by smola** [comment]
To be supported soon, since they are now implemented in go-mysql-server: https://github.com/src-d/go-mysql-server/issues/390

**Comment by erizocosmico** [comment]
Fixed, it's already working on master.
