### ISSUE TITLE
Usage of persistent caches for UAST

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#578]
# UAST packfiles

## Generate them

- Generate them using a gitbase new command? or custom SQL command?
- add some constraints of the files to parse? (references? commit number? both?)
- Custom IDX file implementation?
- How the UAST blobs will be organized on the packfile? referenced by a master commit to several entries?
- The name of the tree entry?
- How to handle corner case of blobs with different paths? 
- How to keep track of already processed blobs? index on memory?
- should we save the driver version used to generate that UAST, if yes, where?
- Should we use timeouts to generate this packfile? (If yes, the content of this packfile might be different in some cases even if source data is the same)

## Use them instead of calling to Bblfsh

- Load custom IDX file and check it before call bblfsh?

## Invalidate them

- Should we invalidate pre-generated UASTs if the driver version has been changed? if yes, how? Invalidating the entire packfile? (Note that if we want to invalidate only some objects from the packfile, we need to generate a new packfile).
- Trigger a new UAST preprocessing should delete old generated packfiles? If the answer is no, How should we handle both generated packfiles that might contain some repeated objects?
- take into account updates on repositories. How? deleting the whole generated packfile?

**Comment by erizocosmico** [comment]
> How to handle corner case of blobs with different paths?

We can have an index that given a file path points to the blob offset in the packfile. We can have them sorted so they're binary searchable.

In fact, it should be a combination of tree_hash and file_path, because a file_path can point to different blobs in time

Are we going to use deltas to reduce space or for now just keeping them all on disk?

**Comment by ajnavarro** [comment]
> We can have an index that given a file path points to the blob offset in the packfile. We can have them sorted so they're binary searchable.

This will be a custom index for this use case, right? (no one already implemented on go-git or standard git fill our use case).

> Maybe the most user-friendly way would be to use a SQL command. But that requires possibly using non-standard syntax.

We have a hard limit to avoid special SQL commands that are not in MySQL. We should find some command that fit on our use case.
