### ISSUE TITLE
UASTs functions: add as warnings only parsing errors on bblfsh functions.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#603]
Connection errors (and other kind of unexpected errors) after retries should make the query fail.

**Comment by erizocosmico** [comment]
Aren't UDFs supposed to not fail?

**Comment by ajnavarro** [comment]
we should fail if something under the hood is failing for other reasons than parsing a file. We should fail when:

- bblfsh is disconnected, we retry N times, and we weren't able to connect to it again.
- bblfsh throw an internal error parsing a file (no parsing error, just a bug in bblfsh).

**Comment by erizocosmico** [comment]
We can guess when bblfsh is disconnected, but not when it's an internal error parsing a file. Parse call just returns an error, we don't know which kind of error it is.
