### ISSUE TITLE
Branch protected from push -f but not direct commits

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#614]
So by mistake I edited the README.md adding a reference to source{d} Engine.
I did it directly on GitHub, and instead of choosing "create a new branch" I mistakenly committed to master.

I then tried to fix it and create the branch instead. To do so I made `master` point to the previous commit on my laptop and then did `push -f`.

Unfortunately that was rejected by a hook, which means I was able to make a mistake ... but not able to fix it.

We should make sure these protections are correctly set-up for all of our projects.

cc @smola

**Comment by ajnavarro** [comment]
Master is protected. Maybe you have special permissions?

**Comment by campoy** [comment]
Oh, let me add "protected and include admins"

**Comment by campoy** [comment]
Success!
<img width="475" alt="screen shot 2018-11-08 at 4 58 59 pm" src="https://user-images.githubusercontent.com/2237452/48236559-9ed25d00-e377-11e8-9311-2973824893e7.png">
