### ISSUE TITLE
Go panic on SQL query

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#615]
This seems like a fun one, when you compare a list to a string you get this cool panic:

```
Query Failed - unknown error: unable to cast []interface {}{"DirectoryOfThisScript", "MakeRelativePathsInFlagsAbsolute", "FlagsForFile"} of type []interface {} to string
```

The query generating this is indeed incorrect, but the error message should be better.

```sql
  SELECT UAST_EXTRACT(UAST(f.blob_content, LANGUAGE(f.file_path, f.blob_content), '//Identifier'), 'Name') as names
  FROM   files AS f
  WHERE  names != ''
```

Replacing the condition with `WHERE names IS NOT NULL` will fix the error, but the message should be more clear.

**Comment by kuba--** [comment]
current gitbase master does not complain on this query

**Comment by kuba--** [comment]
The error comes from `spf13/cast` package. This PR: https://github.com/src-d/go-mysql-server/pull/556, makes an error clearer but less tech. detailed. You'll get:
`incompatible conversion to SQL type:...`
