### ISSUE TITLE
Check what happens when we modify a repo now using gitbase

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#633]
Check the effects on adding, deleting, fetching, pushing and so on, on a git repository from gitbase side. We need to know if something started to go wrong when this happens. Make a report on this issue before doing any change.

**Comment by kuba--** [comment]
I think it's very related to the other research issue: https://github.com/src-d/gitbase/issues/634
I've put some comments which also may cover this issue.
@ajnavarro, @jfontan - PTAL

**Comment by ajnavarro** [comment]
Yep, I think we can close this one in favor of #634
