### ISSUE TITLE
Validate XPath query before use it with the new bblfsh api

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#635]
More info here: https://github.com/bblfsh/sdk/blob/4ba719e80ab52f2d4da5ac8a6f4675687c6fe952/uast/query/xpath/xpath.go#L22

**Comment by kuba--** [comment]
@ajnavarro, @bzz 
I think we already uses the new _stuff_!

In function `func (u *uastFunc) getUAST` we call `nodeArray, err = applyXpath(node, xpath)` (https://github.com/src-d/gitbase/blob/master/internal/function/uast.go#L250)

`applyXpath` calls `it, err := tools.Filter(n, query)` (where tools.Filter is gopkg.in/bblfsh/client-go.v3/tools/context.go#L116)
It creates a new context with `xpath: xpath.New(),` and calls `xpath.Execute`:
```go
if query == "" {
		query = "//*"
}
return c.xpath.Execute(c.root, query)
```

where c.xpath.Execute is exactly the function:
https://github.com/src-d/gitbase/blob/master/vendor/gopkg.in/bblfsh/sdk.v2/uast/query/xpath/xpath.go#L30


So every time when we apply xpath via `tools` wrapper we compile and execute xpath.

**Comment by ajnavarro** [comment]
@kuba-- but we are not failing the query if the xpath is wrong, maybe we should fail on that case.

**Comment by kuba--** [comment]
It should be fixed by 3rd party package: https://github.com/antchfx/xpath/blob/master/xpath.go#L139

**Comment by ajnavarro** [comment]
Related: https://github.com/bblfsh/sdk/issues/332

**Comment by kuba--** [comment]
If we switch to the `gopkg.in/xmlpath.v2`at least in following test it can find the last invalid xpath (`github.com/antchfx/xpath` is the lib. which bblfsh uses right now):
```go
package main

import (
	. "gopkg.in/xmlpath.v2"
	// . "github.com/antchfx/xpath"
)
func main() {
	MustCompile("//*[@role=\"Return\"]")
	MustCompile("BAD")

	MustCompile("this is a totally crap. For sure not valid @xpath") // <----
}
```

**Comment by erizocosmico** [comment]
What shall we do with this? @ajnavarro

**Comment by ajnavarro** [comment]
we can close this as cannot be fixed from our side.
