### ISSUE TITLE
Watch directory with repositories for changes

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase#645]
1. It would be nice to discover new repositories without restart
2. Now sure how gitbase behaves now if a repository is deleted/changed. Would be cool to handle such cases correctly.

**Comment by ajnavarro** [comment]
Actually, this is not possible. If some repository is detached/attached and you have some indexes on them, that indexes will not be correct. See https://github.com/src-d/gitbase/issues/580

**Comment by ajnavarro** [comment]
Shall we close this one @smola ?

**Comment by smola** [comment]
@ajnavarro Yes, I'd say this is a duplicate of https://github.com/src-d/gitbase/issues/580

**Comment by ajnavarro** [comment]
Closing as duplicated then.
