### ISSUE TITLE
Couple of question / issues on the standalone installation of gitbase

### ISSUE THREAD

**Issue by deepakorantak** [src-d/gitbase#649]
I have done a standalone installation of the gitbase server.I started the server providing the git directory pat. When I launch the mysql client using the following command - 
**mysql -q -u root -h 127.0.0.1** 

I get the mysql prompt . When I execute the following query -
 
**mysql> select * from repositories;**
+---------------+
| repository_id |
+---------------+
+---------------+ 

I get empty directory. So not sure how to troubleshoot this issues. As there is no much documentation around how to stop / purge the gitbase server.

**Comment by ajnavarro** [comment]
Hello @deepakorantak 

You should provide a folder with several git repositories, not only the git folder itself.

If you only want to process one repository, put it in a folder, and provide that folder to gitbase.

Hope that helps.

**Comment by deepakorantak** [comment]
I have done that but it did not work. How can you use the same port and host for gitbase's mysql schema?

**Comment by kuba--** [comment]
@deepakorantak - just in case try:
```
use gitbase;
select * from repositories;
```

Questions:
- Can you give us a command line how did you start gitbase?
- If I give you a docker-compose file (with bblfsh and gitbase), will you able to try it out?
- Can you get some gitbase logs when the server is starting?

**Comment by erizocosmico** [comment]
Hi @deepakorantak, try the following:

```
mkdir -p ~/repos-test
git clone https://github.com/src-d/gitbase ~/repos-test/gitbase
path/to/gitbase server --host=127.0.0.1 --port=3306 -d ~/repos-test
```

Then:

```
mysql --host=127.0.0.1 --port=3306 -u root
```

Does the query still return empty results?

**Comment by deepakorantak** [comment]
@kuba - This is how connect to gitabase 
root@ip-172-31-34-50:~# mysql -q -u root -h 127.0.0.1
mysql: [ERROR] Found option without preceding group in config file /etc/mysql/conf.d/my.cnf at line 1!
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.5.10-Vitess

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use gitbase;
Database changed
mysql> select * from repositories;
+---------------+
| repository_id |
+---------------+
+---------------+
0 rows in set (0.00 sec)

**Comment by deepakorantak** [comment]
Just to give you the port status - 
root@ip-172-31-34-50:~# netstat -tulpn | grep LISTEN
**tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      14382/gitbase**
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1037/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      8627/apache2
tcp6       0      0 :::80                   :::*                    LISTEN      8627/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1037/sshd
tcp6       0      0 :::9432                 :::*                    LISTEN      7170/bblfshd

**Comment by kuba--** [comment]
My question was how did you start gitbase. Based on your last command, this is directory where you should have repos:
`~/sourced/git/source-d`.

The error which you got is because your container is still running so port 3306 is in use.
Either stop the container and try again or run gitbase on different port

**Comment by deepakorantak** [comment]
root@ip-172-31-34-50:~/sourced/git/source-d# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

There is no container currently running on the VM

**Comment by erizocosmico** [comment]
Hi @deepakorantak, try the following:

```
mkdir -p ~/repos-test
git clone https://github.com/src-d/gitbase ~/repos-test/gitbase
path/to/gitbase server --host=127.0.0.1 --port=3308 -d ~/repos-test
```

Then:

```
mysql --host=127.0.0.1 --port=3308 -u root
```

Does the query still return empty results?

**Comment by kuba--** [comment]
@deepakorantak - ok, your docker process is not running, but something occupies the port.
But port doesn't matter (it doesn't matter if you run it on 3306 or any other).
Here you run gitbase in interactive mode (not as a daemon or background process), so either open a new terminal, or run gitbase in screen mode, or move it to the background by adding `&` to your command.

**Comment by deepakorantak** [comment]
ok...can you please give me exact command to move it to background ?

**Comment by kuba--** [comment]
`gitbase server --host=127.0.0.1 --port=3308 -d ~/repos-test/ -i ~/tmp/index > /dev/null 2>&1 &`

**Comment by erizocosmico** [comment]
@deepakorantak `-i` is the folder where data from gitbase indexes will be stored. `2>&1` redirects `stderr` to `stdout`.

**Comment by ajnavarro** [comment]
Closing as resolved.
