### ISSUE TITLE
Use full path as repository_id

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase#681]
I have a repos structure like

```
/repositories
 - /owner
    - /repo
```

Sometimes repo names can be the same. In such case on gitbase start I see in logs:
```
time="2019-01-23T12:04:32Z" level=debug msg="repository added" path=/mnt/repositories/SignalR/SignalR
time="2019-01-23T12:04:32Z" level=error msg="repository could not be added" error="the repository is already registered: /mnt/repositories/SignalR/SignalR" id=SignalR path=/mnt/repositories/aspnet/SignalR
time="2019-01-23T12:04:32Z" level=debug msg="repository added" path=/mnt/repositories/aspnet/SignalR
```

Repos https://github.com/aspnet/SignalR and https://github.com/SignalR/SignalR are actually different but only one gets registered and available to query.

**Comment by erizocosmico** [comment]
Blocked until we have a proper discussion about how to implement this correctly.

**Comment by mcuadros** [comment]
All the repository_id handling will be done by go-borges in the near future, maybe worth to fix this, maybe not.

**Comment by bart-y** [comment]
I need it !

**Comment by mcuadros** [comment]
The ID should be relative to the ` --directories=` paths, but ever from the root otherwise the ids are going to be deployment dependent

**Comment by smola** [comment]
As we discussed recently, we need this sooner than later. While we can sometimes workaround with `remotes`, it's not that convenient for our work on PoCs. So if there is enough bandwidth, I think we should fix this even before go-borges integration.
