### ISSUE TITLE
commit_files is not squashed with blobs

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase#687]
Right now we're not squashing commit_files and blobs (or at least not for this query), but they can be squashed AFAIK.

```sql
SELECT DISTINCT
r.repository_id,
LANGUAGE(file_path, blob_content) AS language
FROM refs r
NATURAL JOIN commit_files
NATURAL JOIN blobs
WHERE r.ref_name = 'HEAD' AND language != ''
```

**Comment by ajnavarro** [comment]
As far as I understand, commit_files is just intended to be used to join commits and files tables.

To make that query works, I think the correct way to do it is applying all the necessary joins to get files from commits:

```sql
EXPLAIN FORMAT=tree
SELECT DISTINCT
r.repository_id,
LANGUAGE(file_path, blob_content) AS language
FROM refs r
NATURAL JOIN ref_commits
NATURAL JOIN commit_files
NATURAL JOIN files
WHERE r.ref_name = 'HEAD' AND language != ''
```

@erizocosmico don't hesitate to correct me if I'm missing something.

**Comment by erizocosmico** [comment]
It's intended to work that way, but commit_files has `blob_hash` and `repository_id` so there is no reason why it can't be joined with `blobs`. We can leave it, as it's not a very important thing, but users may want to join with blobs and not understand why it takes so long without knowing these two are not squashable.

**Comment by smola** [comment]
If they can be squashed while maintaining correct results, this would be nice from a user perspective.

**Comment by ajnavarro** [comment]
@smola If we want to go this way, when should we stop? permutations to squash all possible combinations between tables are huge.

**Comment by erizocosmico** [comment]
All other combinations (that make sense) are already covered. This is the only missing one AFAIK.
