### ISSUE TITLE
Gitbase support for low-level git functions

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#692]
Related with #676

**Comment by kuba--** [comment]
Shall we mark it as blocked till we resolve #676 ?

**Comment by erizocosmico** [comment]
Can we add to the issue a bit more of information as to what is a "low-level git UDF"?

**Comment by ajnavarro** [comment]
I don't know exactly what they are, but the idea here is to have UDFs that has access directly to the repository instance, to do more complicated things.

**Comment by erizocosmico** [comment]
So just like UDFs but get another extra param that it's the repo?

**Comment by mcuadros** [comment]
Yes, we can work on this already, we need to access the repository (from `sql.Context` in the UDFs), for sure this will be need it.

**Comment by ajnavarro** [comment]
I would say to close this issue. Right now we are able to access the repository pool inside the context from any Expression. The only thing you need to do is send the repository_id as a function parameter, to be able to retrieve the needed repo.

**Comment by smola** [comment]
I changed the title from _UDF_ to _functions_, which is what we originally meant, even if we said _UDFs_. The case for this is being able to write functions like `DIFF`, where you need to access the repo and you don't have all info as expression inputs (only repository_id and, for example, commit_hash). As far as I know, this can already be done with the context, but it would be good to document it. Once we have at least one function like `DIFF` working, I think we can consider this as fully solved.

**Comment by ajnavarro** [comment]
https://github.com/src-d/gitbase/pull/811

**Comment by smola** [comment]
As far as I can tell, there was a discussed resolution for this, can someone update here accordingly?
cc @src-d/data-processing

**Comment by ajnavarro** [comment]
Already supported and some repository-aware functions implemented: https://github.com/src-d/gitbase/pull/835
