### ISSUE TITLE
Document gitbase audit logs and RBAC

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#693]

**Comment by ajnavarro** [comment]
@smola do we want something more than this? https://docs.sourced.tech/gitbase/using-gitbase/configuration#user-credentials

**Comment by erizocosmico** [comment]
@ajnavarro what shall we do with this?

**Comment by ajnavarro** [comment]
Closing as done: https://docs.sourced.tech/gitbase/using-gitbase/security
