### ISSUE TITLE
Unable to fetch last commit of each repository

### ISSUE THREAD

**Issue by ayushi04** [src-d/gitbase#696]
Hi 
I am trying to fetch last commit of each repository using below query and I am getting message as 'Returned 0 rows (0.038 seconds)'. Could you please suggest what might be the issue.  I am querying using engine.

/* Last commit for each repository */
SELECT r.repository_id, commit_author_name, commit_author_when, commit_message
FROM   refs r
       NATURAL JOIN commits
WHERE  r.ref_name = 'HEAD'

**Comment by ajnavarro** [comment]
Hey @ayushi04 ,

Could you check the output of the following query? `SELECT COUNT(*) from repositories`

If the output is 0, you didn't point correctly to a folder with repositories. Check `-d` option for more info: https://docs.sourced.tech/gitbase/using-gitbase/configuration#command-line-arguments

**Comment by ayushi04** [comment]
yes. I am able to run other queries in engine.  I am getting repositories count as 7.

**Comment by ajnavarro** [comment]
I tried to reproduce the error using gitbase versions `v0.19.0-beta3` and `v0.18.1` with no luck. I just copy&paste your query and everything is working as expected using a subset of 340 repositories to test.

Maybe the error could be related with the engine itself instead of gitbase? @carlosms could you help us?

**Comment by ayushi04** [comment]
Thanks for the quick response. I followed following steps:
1) Running the docker image : sudo docker run --rm --name gitbase -p 3306:3306 -v /mnt/virtual_space/lp_mlrepo:/opt/repos srcd/gitbase:latest
2)  starting the MySQL server : MySQL -q -u root -h 127.0.0.1
My sql logs are :
mysql> select * from repositories limit 10;
+---------------+
| repository_id |
+---------------+
| 51ab4eef0925540772d4474d40f33274aafe30f0.siva |
| 54f420159013a9dc81188cdb21799eaaabf822e7.siva |

mysql> SELECT r.repository_id, commit_author_name, commit_author_when, commit_message
    -> FROM refs r
    -> NATURAL JOIN commits
    -> WHERE r.ref_name = 'HEAD';
+---------------+--------------------+--------------------+----------------+
| repository_id | commit_author_name | commit_author_when | commit_message |
+---------------+--------------------+--------------------+----------------+
+---------------+--------------------+--------------------+----------------+

The repository list which I downloaded using below pga command:
pga get -u /lazyprogrammer/ -l python -o lp_mlrepo

Could you please recreate this example and check once. Thanks for the help

**Comment by ajnavarro** [comment]
Now I see why you are not getting any HEAD. Rooted repositories (repositories that are inside the siva files) have no HEAD because they are storing several standard repositories. To be able to get all the HEADS from one rooted repo, you need to do something like:

```sql
SELECT 
	refs.ref_name, 
	r.repository_id, 
	commit_author_name, 
	commit_author_when, 
	commit_message 
FROM refs r 
NATURAL JOIN commits 
WHERE substring(r.ref_name,1,15) = 'refs/heads/HEAD';
```

**Comment by ayushi04** [comment]
Yes. That worked. Thanks a lot for the help.
