### ISSUE TITLE
Unable to execute a query : working in case of smaller datasets, but fails when dealing with larger datasets

### ISSUE THREAD

**Issue by ayushi04** [src-d/gitbase#697]
Hi,

I am running a query on a smaller dataset and it is running fine. However, when I execute the same query on dataset with repository counts approximately 2000, I am unable to fetch details. I am running below command:

```
SELECT f.repository_id, f.file_path,
       LANGUAGE(f.file_path, f.blob_content) AS lang, f.blob_content,
       UAST(f.blob_content, LANGUAGE(f.file_path, f.blob_content)) AS uast
FROM   refs AS r
       NATURAL JOIN commit_files
       NATURAL JOIN files AS f
WHERE substring(r.ref_name,1,15) = 'refs/heads/HEAD' and f.file_path like '%py' and 
(f.blob_content REGEXP 'pandas' or f.blob_content REGEXP 'keras' or f.blob_content REGEXP 'sklearn' or f.blob_content REGEXP 'theano' or f.blob_content REGEXP 'tensorflow') limit 10;
```

and I am getting below error in gitbase:

> ERROR 1105 (HY000): unknown error: unable to establish a connection with the bblfsh server: context deadline exceeded

and on gitbase web I am getting : 

> Query Failed - unknown error: object not found

Above query is working fine on smaller dataset. 
I am using below command to get all the siva files (in the dataset where I am facing the issue) :
```
sudo cat all_python_gits.json | jq -r &apos;select(.forkCount &gt;= 50) | .sivaFilenames[]&apos; | pga get -i -o all_python_codes
```

**Comment by ajnavarro** [comment]
> ERROR 1105 (HY000): unknown error: unable to establish a connection with the bblfsh server: context deadline exceeded

To be able to use `UAST` UDF, you need to have up and running bblfsh. More info here: https://docs.sourced.tech/gitbase/using-gitbase/getting-started

> Query Failed - unknown error: object not found

Appears that some repository is missing some objects.

You can use `GITBASE_SKIP_GIT_ERRORS=true` to allow the query to continue, even if there are some missing objects. More info here: https://docs.sourced.tech/gitbase/using-gitbase/configuration#environment-variables

**Comment by ajnavarro** [comment]
I will close this issue as resolved, we didn't have any response in 20 days. If you have any other issue don't hesitate to open it.
