### ISSUE TITLE
Migrating the dataset from gitbase to microsoft sql server

### ISSUE THREAD

**Issue by ayushi04** [src-d/gitbase#700]
Hi,

Could you please share the documentation for taking the exporting of dataset in gitbase and importing the dataset in Microsoft sql server. In other works I have list of siva files and I want to work on microsoft sql server. Is it possible?

Thanks in advance.

Regards
Ayushi

**Comment by ajnavarro** [comment]
You can use `mysqldump` to extract that information. Something like:
```
mysqldump --all-databases --port=3306 --host=localhost --protocol=tcp --user=user -ppass --skip-triggers
```

I don't know if the output will be compatible with Microsoft SQL server.

Also, the `files` and `ref_commits` tables can contain potentially millions of rows, so the dump will take forever.

If instead to import everything you want only a subset of the data, you can use any of the supported languages to make a script and export it: https://github.com/src-d/go-mysql-server/blob/master/SUPPORTED_CLIENTS.md

**Comment by ajnavarro** [comment]
I will close this issue as resolved, we didn't have any response in 20 days. If you have any other issue don't hesitate to open it.
