### ISSUE TITLE
Make configurable default bblfsh UAST flavour

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#703]
To mitigate this problem: https://github.com/src-d/gitbase-spark-connector/issues/76
we should be able to configure the UAST default output type from an environment variable.

**Comment by smola** [comment]
Preferably not: environment variables might be controlled by a different user (e.g. in our case, infra, not developer/analyst), then some queries will be not valid depending on such deployment config. This is the same problem we had for regexps.

**Comment by ajnavarro** [comment]
we will limit the usage of UAST UDF at GSC level.
