### ISSUE TITLE
Repo cannot be added error="The repo is already registered"

### ISSUE THREAD

**Issue by srinivasanraghavan** [src-d/gitbase#710]
I am trying to add a large number of Go repo in git base .. I am getting this error . Can some one help 
![screenshot 2019-02-26 at 3 06 30 pm](https://user-images.githubusercontent.com/4154181/53393852-70d16100-39d8-11e9-8ce5-666147722f19.png)

**Comment by smola** [comment]
@srinivasanraghavan What version of gitbase are you using? Which command are you using to start it? Do you have multiple repos with the same name (maybe forks)?

**Comment by srinivasanraghavan** [comment]
Sry for the delayed response i work in the Singapore time zone 

This is version gitbase_v0.19.0-beta4_linux_amd64.tar.gz . 

The command used in gitbase server -d /path 

Folder has forks . U could end up when same repo name ..  

Like organisation/jdk11 and srinivasan/jdk11

**Comment by ajnavarro** [comment]
We have an open issue for this problem: https://github.com/src-d/gitbase/issues/681

A quick workaround is to rename that folders that are forked from originals.

**Comment by srinivasanraghavan** [comment]
Thank you
