### ISSUE TITLE
Sever restart questions

### ISSUE THREAD

**Issue by srinivasanraghavan** [src-d/gitbase#712]
Eg gibase sever -d /path1

When i kill the server and restart it. Would the git repo be parsed again and loaded into the DB. Or would it load only the diff if the /path1 has been updated ?

gitbase server -d / path2 

When i kill server and give another path2 I see now the DB would  only the new path2 data . So would be old info be pruged or would it be backed up in a dump or some other way ?

**Comment by ajnavarro** [comment]
Hello @srinivasanraghavan 

Gitbase is not loading the git data into a database, we are **directly** reading the information on repositories and showing it to the user in a tabular representation.

If you execute gitbase on path1, you will see all the data from repositories on path1. The same if you do the process with path2, you will only see info from repositories on this path.

Hope it helps.

**Comment by srinivasanraghavan** [comment]
So typical use case for gitbase  is to use this to generate a small DB on the fly use classic sql to manipulate data  and store it else where. Am i correct.

**Comment by ajnavarro** [comment]
You can query and get insights directly using gitbase, or you can export the obtained data elsewhere if you want too. 

Depending on the size and amount of repositories, the obtained data from tables without filtering might be humongous and hardly possible to handle by a standard SQL database.

**Comment by erizocosmico** [comment]
Closing, as the question has already been solved.
