### ISSUE TITLE
Limit directive takes a lot on commits table

### ISSUE THREAD

**Issue by dpordomingo** [src-d/gitbase#725]
Querying one commit takes a lot,
```SQL
select commit_author_name from commits limit 1
```

"exactly" the same than counting all of them:
```SQL
select count(*) from commits
```

If you run it from a db backing only one single repo, that time is "exactly" the same that the time needed by `go-git` to traverse the whole history of that repo from `HEAD`. (using, for example, this `go-git` [command](https://gist.github.com/dpordomingo/25722d501803208d623b749115d2f20e))

### How to reproduce;

I tried with `linux` repository doing the following:

```shell
gitbase server --port=3306 \
    --directories=$GOPATH/src/github.com/torvalds/linux \
    --index=/tmp/gitbase
```
log:
<details><pre>
INFO[0000] squash tables rule is enabled
INFO[0000] server started and listening on localhost:3306

INFO[0005] NewConnection: client 1
ERRO[0005] Error parsing auth server config: unexpected end of JSON input
INFO[0005] audit trail                  action=authentication address="127.0.0.1:39122" success=true system=audit user=root
INFO[0005] audit trail                  action=authorization address="127.0.0.1:39122" connection_id=1 permission=read pid=1 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0005] audit trail                  action=query address="127.0.0.1:39122" connection_id=1 duration=13.467911ms pid=1 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0005] audit trail                  action=authorization address="127.0.0.1:39122" connection_id=1 permission=read pid=2 query="select count(*) from commits" success=true system=audit user=root

INFO[0019] NewConnection: client 2
INFO[0019] audit trail                  action=authentication address="127.0.0.1:39124" success=true system=audit user=root
INFO[0019] audit trail                  action=authorization address="127.0.0.1:39124" connection_id=2 permission=read pid=3 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0019] audit trail                  action=query address="127.0.0.1:39124" connection_id=2 duration="370.886µs" pid=3 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0019] audit trail                  action=authorization address="127.0.0.1:39124" connection_id=2 permission=read pid=4 query="SHOW PROCESSLIST" success=true system=audit user=root
INFO[0019] audit trail                  action=query address="127.0.0.1:39124" connection_id=2 duration="116.002µs" pid=4 query="SHOW PROCESSLIST" success=true system=audit user=root
INFO[0019] ConnectionClosed: client 2

INFO[0059] audit trail                  action=query address="127.0.0.1:39122" connection_id=1 duration=54.592418087s pid=2 query="select count(*) from commits" success=true system=audit user=root
INFO[0059] ConnectionClosed: client 1

INFO[0113] NewConnection: client 3
INFO[0113] audit trail                  action=authentication address="127.0.0.1:39134" success=true system=audit user=root
INFO[0113] audit trail                  action=authorization address="127.0.0.1:39134" connection_id=3 permission=read pid=5 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0113] audit trail                  action=query address="127.0.0.1:39134" connection_id=3 duration=1.356734ms pid=5 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0113] audit trail                  action=authorization address="127.0.0.1:39134" connection_id=3 permission=read pid=6 query="select commit_author_name from commits limit 1" success=true system=audit user=root

INFO[0120] NewConnection: client 4
INFO[0120] audit trail                  action=authentication address="127.0.0.1:39138" success=true system=audit user=root
INFO[0120] audit trail                  action=authorization address="127.0.0.1:39138" connection_id=4 permission=read pid=7 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0120] audit trail                  action=query address="127.0.0.1:39138" connection_id=4 duration=1.068485ms pid=7 query="select @@version_comment limit 1" success=true system=audit user=root
INFO[0120] audit trail                  action=authorization address="127.0.0.1:39138" connection_id=4 permission=read pid=8 query="SHOW PROCESSLIST" success=true system=audit user=root
INFO[0120] audit trail                  action=query address="127.0.0.1:39138" connection_id=4 duration="215.487µs" pid=8 query="SHOW PROCESSLIST" success=true system=audit user=root
INFO[0120] ConnectionClosed: client 4

INFO[0178] audit trail                  action=query address="127.0.0.1:39134" connection_id=3 duration=1m4.758952886s pid=6 query="select commit_author_name from commits limit 1" success=true system=audit user=root
INFO[0178] ConnectionClosed: client 3
</pre></details>

```shell
$ time mysql --port=3306 --user=root --host=127.0.0.1 \
    --execute "select commit_author_name from commits limit 1"
+--------------------+
| commit_author_name |
+--------------------+
| Linus Torvalds     |
+--------------------+
real	0m53.961s
user	0m0.000s
sys	0m0.004s

$ time mysql --port=3306 --user=root --host=127.0.0.1 \
    --execute "select count(*) from commits"
+----------+
| COUNT(*) |
+----------+
|   812648 |
+----------+

real	0m54.624s
user	0m0.008s
sys	0m0.004s

$ wget https://gist.githubusercontent.com/dpordomingo/25722d501803208d623b749115d2f20e/raw/533280fb5e355f81f54b77785551541e1aabc380/count_commits.go
$ time go run go run count_commits.go .
812644

real	0m54.823s
user	1m0.632s
sys	0m5.968s
```

```shell
$ mysql --port=3306 --user=root --host=127.0.0.1
    --execute "SHOW PROCESSLIST;"
+------+------+---------+---------+---------+------+--------------+--------------------------------------+
| Id   | User | db      | Command | Time | State        | Info                                           |
+------+------+---------+---------+---------+------+--------------+--------------------------------------+
|    6 | root | gitbase | query   |   53 | commits(0/1) | select commit_author_name from commits limit 1 |
|    2 | root | gitbase | query   |   54 | commits(0/1) | select count(*) from commits                   |
+------+------+---------+---------+------+--------------+------------------------------------------------+
```

**Comment by dpordomingo** [comment]
`blobs` table behave differently, what I think it's ok

```shell
$ time mysql --port=3306 --user=root --host=127.0.0.1 \
    --execute "select count(*) from blobs"
+----------+
| COUNT(*) |
+----------+
|  1836000 |
+----------+

real	2m18.616s
user	0m0.012s
sys	0m0.004s


$ time mysql --port=3306 --user=root --host=127.0.0.1 \
    --execute "select repository_id, blob_hash, blob_size from blobs limit 1"
+---------------+------------------------------------------+-----------+
| repository_id | blob_hash                                | blob_size |
+---------------+------------------------------------------+-----------+
| linux         | 00fde393e10fafa1a89fbc789ba9d266170605c8 |      4924 |
+---------------+------------------------------------------+-----------+
real	0m0.159s
user	0m0.004s
sys	0m0.008s
```

**Comment by kuba--** [comment]
@jfontan could you transfer this issue to `go-git` repo. Commit iterator has to have `LogOptions{All:true}` (otherwise select from commits returns an empty result for siva files), so instead of fixing performance on gitbase, we should improve `git log --all` algorithm in `go-git`
