### ISSUE TITLE
Regression: object not found error

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#741]
The following query:

```sql
SELECT 
	repository_id,
	contributor_count 
FROM (
	SELECT 
		repository_id, 
		COUNT(DISTINCT commit_author_email) AS contributor_count 
	FROM commits 
	GROUP BY repository_id
) AS q 
ORDER BY contributor_count DESC 
LIMIT 10
```

Throw an `object not found` error

**Comment by ajnavarro** [comment]
It is happening again on actual master branch 1a83350d

It also happens with `select count(*) from commits`.

**Comment by erizocosmico** [comment]
Can't reproduce. What dataset are you using?

**Comment by ajnavarro** [comment]
False alarm, I accidentally tried with a shallow repository.
