### ISSUE TITLE
make static-package is not working properly

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#778]
See: https://travis-ci.com/src-d/gitbase/jobs/190291212#L1566

**Comment by juanjux** [comment]
The problem seems to be that https://hub.docker.com/r/srcd/gitbase/tags doesn't have that version.

**Comment by ajnavarro** [comment]
Not fixed: https://travis-ci.com/src-d/gitbase/jobs/191104986#L1565

**Comment by juanjux** [comment]
The `make ci-e2e` problem seems to be fixed, but not the one for `make static-package`. One question, since it seems `static-package` uses the docker hub image, where is that supposed to be created and pushed to dockerhub? (it's missing right now).

**Comment by kuba--** [comment]
we don't push `-beta` (or with any other suffix) images.
