### ISSUE TITLE
Compatibility with Apache Superset

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#784]
We're considering using [Apache Superset](https://github.com/apache/incubator-superset) to generate dashboards. Both for gitbase and gitbase-spark-connector. So we need to work on compatibility for it. If there is any major functionality that cannot be done in short-term, input on what it would take to support it will also be needed.

**Comment by mcuadros** [comment]
In a preliminary review I found this incompatibilities:
- Missing `DATE` function (https://github.com/src-d/go-mysql-server/pull/654)
- Missing `DATE_SUB` and `DATE_ADD` functions
- Incompaitbile `SHOW CREATE TABLE` result with SQLAlchemy (https://github.com/src-d/go-mysql-server/pull/656)
- using fqns in `SHOW CREATE TABLE` errors (https://github.com/src-d/gitbase/issues/787)

**Comment by erizocosmico** [comment]
* DATE_SUB and DATE_ADD https://github.com/src-d/go-mysql-server/issues/663

**Comment by mcuadros** [comment]
I just added support for `HAVING`, since some charts require this, without having a easy alternative on the GUI to generate other kind of query.

What about https://github.com/src-d/go-mysql-server/pull/599? /cc @smola @ajnavarro

**Comment by ajnavarro** [comment]
@mcuadros https://github.com/src-d/go-mysql-server/pull/599 needs more work to make rules work as expected in some cases.

**Comment by kuba--** [comment]
Let's split this kind of EMPIC into multiple small tasks. So far, it looks that everything is either done, blocked by 3rdparties or requires much more effort.

**Comment by mcuadros** [comment]
Well, this issue is still pending, what I wrote is my initial research but a more depth list should be created after going through all the options of Superset

**Comment by erizocosmico** [comment]
HAVING support at https://github.com/src-d/go-mysql-server/pull/689

**Comment by ajnavarro** [comment]
Closing as completed; https://github.com/src-d/gitbase/releases/tag/v0.20.0-beta4 is compatible with superset.
