### ISSUE TITLE
Images are broken in gitbook documentation

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#792]
Images are broken in gitbook documentation. Example:

![2019-04-10-095944_1736x687_scrot](https://user-images.githubusercontent.com/23248/55861801-742f3f00-5b77-11e9-911f-4e2918933705.png)

**Comment by ajnavarro** [comment]
@smola I don't have that problem. Are you checking latest release or master documentation?

**Comment by smola** [comment]
@ajnavarro https://docs.sourced.tech/gitbase/using-gitbase/schema at the end of the page

**Comment by ajnavarro** [comment]
Yeah, I know, but I'm able to see it:

![screenshot-docs sourced tech-2019 04 16-09-27-17](https://user-images.githubusercontent.com/1196465/56190126-ded5f400-6029-11e9-85dc-898aa7fe6eab.png)

**Comment by smola** [comment]
@ajnavarro Indeed. [Privacy Badger](https://www.eff.org/privacybadger) was blocking gitbook's CDN domain.
