### ISSUE TITLE
Function reference in gitbook documentation

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#793]
Current _[Supported syntax](https://docs.sourced.tech/gitbase/using-gitbase/supported-syntax)_ links to [go-mysql-server documentation](https://github.com/src-d/go-mysql-server/blob/3dd441325d1731821eff0495fbf63747c258b8ff/SUPPORTED.md). It reads:

> To see the SQL subset currently supported take a look at this list from src-d/go-mysql-server.

I think we should include it right in the gitbook, and specially for the functions, have their signature and some description.

**Comment by erizocosmico** [comment]
To avoid inconsistencies between them, I suggest the following:

- Add `<!-- TAGS LIKE THIS -->` to delimit parts in the readme and some other files in go-mysql-server and gitbase.
- Replace them with newer versions every time we run `make upgrade` script.

That way, gitbase always has the content of the version we're running.
