### ISSUE TITLE
table "commits" does not have column "repository_id"

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase#799]
I got this error making charts in superset but the smallest reproducible sql is:

```sql
SELECT repository_id AS repository_id
FROM commits
GROUP BY repository_id
ORDER BY repository_id
```

**Comment by erizocosmico** [comment]
This should be fixed with https://github.com/src-d/go-mysql-server/pull/680. A version containing this fix has not been released yet, but once it is, this will be fixed.

**Comment by erizocosmico** [comment]
https://github.com/src-d/gitbase/pull/804 will fix this. But I found a regression while updating, so after the regression (https://github.com/src-d/go-mysql-server/pull/690) is merged, I will update again.
