### ISSUE TITLE
Expose metrics on cache hit/miss rates

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#815]
We have quite a few caches in gitbase, but as far as I can tell, we have no way to get metrics for cache hit/miss rates. Those would be very useful for troubleshooting and tuning.

**Comment by kuba--** [comment]
where do you want to store those metrics?
gitbase uses only open tracing, there is no statsD/graphana infra (as far as I know).
We can push this kind of metrics to StatsD or any other time series DB over UDP.

**Comment by smola** [comment]
In our clusters we use Prometheus, which can be setup to retrieve metrics from an HTTP endpoint.

**Comment by kuba--** [comment]
sure thing, my question was- do we want to expose http port?

**Comment by smola** [comment]
@kuba-- Yes, I think so, since we're going that route for other components.
