### ISSUE TITLE
Use go modules

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase#838]
We should make the move to go modules if we want to upgrade bblfsh on gitbase, as they have moved to modules recently.

However, the process of upgrade needs some work on these areas:

- Go modules strip all tests and non-go code and there seems to be no way to change this behaviour. Because of that, the automatic process of copying docs would need to be changed.
- For some reason, versioning with revisions and gopkg.in seems to work really bad. We would also have to move go-mysql-server away from gopkg.in (it already uses modules) or use proper versions, which is a pain because most of the time we don't want to be making versions for each bug fix or so.

**Comment by ajnavarro** [comment]
cc @smola

**Comment by smola** [comment]
> @erizocosmico For some reason, versioning with revisions and gopkg.in seems to work really bad.

Why is that? It seemed to work fine on simpler projects at least.

**Comment by erizocosmico** [comment]
I don't know. It says "revision not found" and just gets the latest version. Replace does help, but replacing is not exactly easy because revisions have a weird format "VERSION-YYYYmmDDHHMMSS-REVISION" and it's not exactly very user friendly or easy to get.
It _can_ be done but it's a real pain, probably because it's not the intended use case. The best scenario to make this work is just use versions for everything and not revisions. But if we use revisions, I'd move away from gopkg.in to not make replacements necessary.

**Comment by jfontan** [comment]
You can do a replace with a revision or tag and its version is generated by the tools:

```
go mod edit -replace gopkg.in/src-d/go-mysql-server.v0=github.com/src-d/go-mysql-server@master
go mod tidy
```

That's how I have it in my `go.mod` enabled gitbase version. But I am with @erizocosmico. Using two versioning systems at the same time (`gopkg.in` and `go.mod`) is cumbersome.
