### ISSUE TITLE
Query takes too much memory

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#840]
Even limiting object cache to the default (512mb), the following query is getting all 16GB on my machine.

```
SELECT c.commit_hash,
	LANGUAGE(f.file_path) as lang,
	SUM(ARRAY_LENGTH(SPLIT(f.blob_content, "\n"))-1) as lines
FROM ref_commits rc
NATURAL JOIN commits c
NATURAL JOIN commit_files cf
NATURAL JOIN files f
WHERE rc.ref_name = 'HEAD'
	AND f.file_path NOT REGEXP '^vendor.*'
	AND NOT IS_BINARY(f.blob_content)
GROUP BY LANGUAGE(f.file_path)
ORDER BY c.commit_author_when
```

**Comment by erizocosmico** [comment]
Even if you limit the cache, that does not mean gitbase is not gonna keep every single blob content in memory.
Both group by and order by compute absolutely all rows and then perform their aggregations, keeping every single row (including the whole blob_content) in memory. If you have a big amount of repositories, this does not look surprising at all.

**Comment by ajnavarro** [comment]
The last query is getting the same amount of memory.

**Comment by erizocosmico** [comment]
Oops, it was without the order by

```sql
SELECT lang, SUM(lines) AS lines
FROM (
    SELECT LANGUAGE(f.file_path, f.blob_content) as lang,
        (ARRAY_LENGTH(SPLIT(f.blob_content, "\n"))-1) as lines
    FROM ref_commits rc
    NATURAL JOIN commits c
    NATURAL JOIN commit_files cf
    NATURAL JOIN files f
    WHERE rc.ref_name = 'HEAD'
        AND cf.file_path NOT REGEXP '^vendor.*'
        AND NOT IS_BINARY(f.blob_content)
) t
GROUP BY lang
```

**Comment by erizocosmico** [comment]
Shall we close this, then?
