### ISSUE TITLE
Implement COMMIT_FILE_STATS

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#858]
Similar to `COMMIT_STATS(repo_id, commit_hash)` function it is receiving `COMMIT_FILE_STATS(repo_id, commit_hash)` and the output will be an array with the following content per element:

```json
 {
	"Path": "/path/to/file.go",
	"Language": "Go",
	"Code":	{
		"Additions":0,
		"Deletions":0
	},
	"Comment": {
		"Additions":0,
		"Deletions":0
	},
	"Blank": {
		"Additions":0,
		"Deletions":0
	},
	"Other": {
		"Additions":0,
		"Deletions":0
	},
	"Total": {
		"Additions":0,
		"Deletions":0
	}
}
```

**Comment by erizocosmico** [comment]
After Slack discussion:
- Vendored files should also be processed here.
