### ISSUE TITLE
Use struct tags on commit_stats and commit_file_stats

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase#930]
Right now all JSON produced by these UDFs has the fields in Uppercase, which is weird when using JSON (specially in Spark, using the struct fields). Should we add some struct tags so it's in `snake_lower_case`?

WDYT @src-d/data-processing?

**Comment by ajnavarro** [comment]
As I answered into the PR, I'm concerned about backward compatibility. All queries that are using these functions will stop working with no error message.
