### ISSUE TITLE
Import path extraction query example is no longer valid

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#933]
This is no longer valid with latest bblfsh version:

https://docs.sourced.tech/gitbase/using-gitbase/examples#extract-all-import-paths-for-every-go-file-on-head-reference

```
uast_extract(uast(blob_content, LANGUAGE(file_path), '//uast:Import/Path'), "Value") AS imports
```

`//uast:Import/Path` is still valid for Go, but the `UAST_EXTRACT(..., "Value")` part no longer applies (thanks @bzz for helping me understanding this)

More info:
- Explanation of different tree structures for imports in UAST: https://github.com/src-d/ml-backlog/issues/65#issuecomment-494187858
- go-driver v2.7.0, the version which introduced this change for Go https://github.com/bblfsh/go-driver/releases/tag/v2.7.0

**Comment by dennwc** [comment]
As a note, we also added [the helper](https://github.com/bblfsh/sdk/blob/master/uast/helpers.go#L14) to properly extract import paths for any language. We will ensure this function works even if UAST structure changes.

**Comment by erizocosmico** [comment]
Will be taken care of as part of https://github.com/src-d/gitbase/issues/936

**Comment by erizocosmico** [comment]
Since imports (in Go at least) can have two forms (uast:Identifier or uast:QualifiedIdentifier) and we have nothing to merge JSON arrays, we can extract them separately.

**Comment by erizocosmico** [comment]
It was deleted until we implement something more convenient, such as the helpers pointed out by Dennis.

**Comment by erizocosmico** [comment]
Shall we close the issue or keep it open until a replacement for getting imports is implemented?

**Comment by ajnavarro** [comment]
Maybe we can close this and open another to implement special bblfsh functions as UDFs, like that one that is extracting imports in the same way in any lang.

**Comment by erizocosmico** [comment]
Closing in favor of #943
