### ISSUE TITLE
Connection problems and possible fix

### ISSUE THREAD

**Issue by juanjux** [src-d/gitbase#946]
From slack by @ajnavarro:

- Adding keepalive at the TCP level.
- Use NewListenerWithConfig and add a cfg.Listener that generates a Conn object we can handle.

net.Conn has two methods: https://golang.org/pkg/net/#TCPConn.SetKeepAlive and https://golang.org/pkg/net/#TCPConn.SetKeepAlivePeriod

**Comment by ajnavarro** [comment]
Related: https://github.com/src-d/gitbase-spark-connector-enterprise/issues/81

**Comment by ajnavarro** [comment]
@juanjux Maybe this issue might be in go-mysql-server repo.

**Comment by juanjux** [comment]
Moved to https://github.com/src-d/go-mysql-server/issues/796
