### ISSUE TITLE
How to find the exact changes for each file in a commit like git diff

### ISSUE THREAD

**Issue by lcwj3** [src-d/gitbase#959]
Hi, this is a powerful tool for parsing git repos. Currently I am trying to find a solution to parse exact line changes in each file for each commit, like git diff. I have read your code, it seems you are also using another tool https://github.com/hhatto/gocloc to count cloc (Maybe I didn't find the right place). Do you have a API or just a solution on parsing the exact changes for files?
Looking forward to your reply, thanks for your attention!

**Comment by ajnavarro** [comment]
Hello @lcwj3 !

To check changes we actually have the following functions (https://docs.sourced.tech/gitbase/using-gitbase/functions#gitbase-functions):

- commit_stats(repository_id, [from_commit_hash], to_commit_hash) json: https://docs.sourced.tech/gitbase/using-gitbase/functions#how-to-use-commit_stats
- commit_file_stats(repository_id, [from_commit_hash], to_commit_hash) json array: https://docs.sourced.tech/gitbase/using-gitbase/functions#how-to-use-commit_file_stats
- loc(path, blob) json: https://docs.sourced.tech/gitbase/using-gitbase/functions#how-to-use-loc

Hope it helps.

**Comment by lcwj3** [comment]
Hi, thanks for your kind reply. I have tried these two API, but it seems these two can only give how many lines are changed in each file, but not exact changed line contents as what git diff does.

**Comment by ajnavarro** [comment]
Sadly we don't have a way to get the content of those changed lines yet. We started some research on how to represent that on a tabular way, but right now is not in the immediate backlog.

**Comment by lcwj3** [comment]
Okay, Thanks anyway! I was using unidiff to get the changed content, which can wrap a commit as a patch, then can access the exact lines, and I think the format in patch is a good enough for me. Maybe this can help you a bit. And I will close this issue now, thanks!
