### ISSUE TITLE
Link to the community edition is dead.

### ISSUE THREAD

**Issue by vonHabsi** [src-d/gitbase#991]
https://sourced.tech/products/community-edition/

The above link is not responding.

**Comment by smola** [comment]
@vonHabsi Sourced is out of business, so all its projects are discontinued.

Some projects got new maintained forks such as go-mysql-server at https://github.com/dolthub/go-mysql-server and go-git at https://github.com/go-git/go-git

Unfortunately, that's not the case with gitbase, so the project is essentially dead.
